CREATE TABLE lattices_all (
    lattice_id    TEXT     -- which lattice (document) it belongs
    )  DISTRIBUTED BY (lattice_id);

CREATE TABLE lattices (
    lattice_id    TEXT     -- which lattice (document) it belongs
    )  DISTRIBUTED BY (lattice_id);

CREATE TABLE lattices_holdout (
    lattice_id    TEXT     -- which lattice (document) it belongs
    )  DISTRIBUTED BY (lattice_id);

CREATE TABLE lattice_meta (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    speaker_id    TEXT,     -- speaker's identifier
    sentenceid    TEXT      -- which sentence for this speaker
    )  DISTRIBUTED BY (lattice_id);


CREATE TABLE candidate (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    source        TEXT,     -- dc / nc / ...
    starts        BIGINT,   -- start from 1
    ends          BIGINT,   -- start from 0, according to source
    word          TEXT,
    confirm       INT,      --  -1 / 0 (sil) / 1
    candidate_id  BIGINT,   -- unique, generated by loading script
    is_true       BOOLEAN,  -- to predict
    id            BIGINT
    )  DISTRIBUTED BY (lattice_id);

CREATE TABLE candidate_all (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    source        TEXT,     -- dc / nc / ...
    starts        BIGINT,   -- start from 1
    ends          BIGINT,   -- start from 0, according to source
    word          TEXT,
    confirm       INT,      --  -1 / 0 (sil) / 1
    candidate_id  BIGINT,   -- unique, generated by loading script
    is_true       BOOLEAN,  -- to predict
    id            BIGINT
    )  DISTRIBUTED BY (lattice_id);

CREATE TABLE candidate_baseline (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    source        TEXT,     -- dc / nc / ...
    starts        BIGINT,   -- start from 1
    ends          BIGINT,   -- start from 0, according to source
    word          TEXT,
    confirm       INT,      --  -1 / 0 (sil) / 1
    candidate_id  BIGINT,   -- unique, generated by loading script
    is_true       BOOLEAN,  -- to predict
    id            BIGINT
    )  DISTRIBUTED BY (lattice_id);

CREATE TABLE candidate_oracle (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    source        TEXT,     -- dc / nc / ...
    starts        BIGINT,   -- start from 1
    ends          BIGINT,   -- start from 0, according to source
    word          TEXT,
    confirm       INT,      --  -1 / 0 (sil) / 1
    candidate_id  BIGINT,   -- unique, generated by loading script
    is_true       BOOLEAN,  -- to predict
    id            BIGINT
    )  DISTRIBUTED BY (lattice_id);

CREATE TABLE f_cand_2gram (
  lattice_id    TEXT,
  candidate_id  BIGINT,
  ngram         TEXT,
  skipping      BOOLEAN
  )  DISTRIBUTED BY (lattice_id);

CREATE TABLE f_cand_3gram (
  lattice_id    TEXT,
  candidate_id  BIGINT,
  ngram         TEXT,
  skipping      BOOLEAN
  )  DISTRIBUTED BY (lattice_id);

CREATE TABLE f_cand_4gram (
  lattice_id    TEXT,
  candidate_id  BIGINT,
  ngram         TEXT,
  skipping      BOOLEAN
  )  DISTRIBUTED BY (lattice_id);

CREATE TABLE f_cand_5gram (
  lattice_id    TEXT,
  candidate_id  BIGINT,
  ngram         TEXT,
  skipping      BOOLEAN
  )  DISTRIBUTED BY (lattice_id);

CREATE TABLE f_pos_2gram (
  lattice_id    TEXT,
  candidate_id  BIGINT,
  ngram         TEXT,
  skipping      BOOLEAN
  )  DISTRIBUTED BY (lattice_id);

CREATE TABLE f_pos_3gram (
  lattice_id    TEXT,
  candidate_id  BIGINT,
  ngram         TEXT,
  skipping      BOOLEAN
  )  DISTRIBUTED BY (lattice_id);


CREATE TABLE f_stopword_2gram (
  lattice_id    TEXT,
  candidate_id  BIGINT,
  ngram         TEXT
  )  DISTRIBUTED BY (lattice_id);

CREATE TABLE transcript (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    wordid        INT,
    word          TEXT
    )  DISTRIBUTED BY (lattice_id);

CREATE TABLE candidate_label (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    candidate_id  BIGINT,   -- unique, generated by loading script
    is_true       BOOLEAN   -- supervision label
  ) DISTRIBUTED BY (lattice_id);

CREATE TABLE transcript_array (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    words         TEXT[]
) DISTRIBUTED BY (lattice_id);

-- CREATE TABLE transcript_array AS
--   SELECT  lattice_id, 
--           ARRAY_AGG(word ORDER BY wordid) AS words
--   FROM    transcript
--   GROUP BY lattice_id
-- DISTRIBUTED BY (lattice_id);

CREATE TABLE output_bestpath (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    words         TEXT[]
) DISTRIBUTED BY (lattice_id);

CREATE TABLE output_oracle (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    words         TEXT[]
) DISTRIBUTED BY (lattice_id);

CREATE TABLE output_baseline (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    words         TEXT[]
) DISTRIBUTED BY (lattice_id);


CREATE TABLE chained_candidates (
    lattice_id     TEXT,
    c1_cid         BIGINT,
    c2_cid         BIGINT
) DISTRIBUTED BY (c1_cid);

CREATE TABLE candidate_pos (
    lattice_id     TEXT,
    candidate_id  BIGINT,   -- unique, generated by loading script
    pos       TEXT   -- supervision label
) DISTRIBUTED BY (lattice_id);