CREATE TABLE candidate (
    lattice_id    TEXT,     -- which lattice (document) it belongs
    source        TEXT,     -- dc / nc / ...
    starts        BIGINT,   -- start from 1
    ends          BIGINT,   -- start from 0, according to source
    word          TEXT,
    confirm       INT,      --  -1 / 0 (sil) / 1
    candidate_id  BIGINT,   -- unique, generated by loading script
    is_true       BOOLEAN,  -- to predict
    id            BIGINT
    )  DISTRIBUTED BY (lattice_id);

CREATE TABLE f_cand_2gram (
  lattice_id    TEXT,
  candidate_id  BIGINT,
  ngram         TEXT
  )  DISTRIBUTED BY (lattice_id);